
const data = 
[
  {
    name: "John Doe",
    street: "123 Main St",
    city: "Cityville",
    state: "ST",
    country: "Countryland",
    telephone: "555-1234",
    birthday: "01/15/1985",
  },
  {
    name: "Jane Smith",
    street: "456 Elm St",
    city: "Mountain",
    state: "AC",
    country: "US",
    telephone : "555-1234",
    birthday: "01/04/1975",
  },
  {
    name: "John Smith",
    street: "234",
    city: "Cotonou",
    state: "Unknown",
    country: "Benin",
    telephone : "97949720",
    birthday: "09/07/2000",
  },
  {
    name: "Alice Johnson",
    street: "789 Oak St",
    city: "Townsville",
    state: "TS",
    country: "Countryland",
    telephone: "555-5678",
    birthday: "05/22/1992",
  },
  {
    name: "Bob Anderson",
    street: "567 Pine St",
    city: "Village",
    state: "AC",
    country: "US",
    telephone : "555-4321",
    birthday: "11/30/1980",
  },
  {
    name: "Sarah Brown",
    street: "890 Maple St",
    city: "Cityville",
    state: "ST",
    country: "Countryland",
    telephone: "555-9876",
    birthday: "07/18/1995",
  },
  {
    name: "David Wilson",
    street: "123 Elm St",
    city: "Mountain",
    state: "AC",
    country: "US",
    telephone : "555-2468",
    birthday: "03/10/1978",
  },
  {
    name: "Sophie Martin",
    street: "345 Oak St",
    city: "Townsville",
    state: "TS",
    country: "Countryland",
    telephone: "555-1357",
    birthday: "09/02/1989",
  },
  {
    name: "Thomas Johnson",
    street: "678 Pine St",
    city: "Village",
    state: "AC",
    country: "US",
    telephone : "555-7890",
    birthday: "12/05/1973",
  },
  {
    name: "Emily Davis",
    street: "901 Maple St",
    city: "Cityville",
    state: "ST",
    country: "Countryland",
    telephone: "555-3698",
    birthday: "08/12/1987",
  },
  {
    name: "Michael Wilson",
    street: "234 Elm St",
    city: "Mountain",
    state: "AC",
    country: "US",
    telephone : "555-6543",
    birthday: "02/25/1971",
  }
];